apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert --out yamls
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: pgadmin
  name: pgadmin
spec:
  ports:
    - name: "5050"
      port: 5050
      targetPort: 80
  selector:
    io.kompose.service: pgadmin
