apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: prom-data
  name: prom-data
spec:
  storageClassName: manual
  volumeName: prom-data-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
